sprint_6-solution
lapochka2019/java-kanban pull request #1
Opened 2024-10-09 08:13 UTC by lapochka2019

2024-10-10 07:26 UTC, vlolad requested changes
Привет!

В целом всё хорошо, новый функционал работает корректно, но пока есть недочеты в плане распределения логики между разными методами в менеджере истории. Описал в комментариях, как можно декомпозировать

В менеджере задач при массовом очищении списка (по типам задач) они не удаляются из истории, это также надо поправить. Там просто добавить один цикл

В остальном хорошо, жду на финальное ревью. Хорошего дня!

2024-10-10 07:26 UTC, vlolad commented on src/service/InMemoryHistoryManager.java
> +    /**Я не очень поняла, для чего нам еще ArrayList*/
1. Он нам и не нужен теперь)
2.` /**Вот такие комментарии с двумя звездами в начале*/ `- это javadoc, они используются для формирования документации (и показываются на всплывашках в IDE). Их для общения с ревьюером и простых пояснений использовать не надо. Лучше просто обычные через /* или //

2024-10-10 07:26 UTC, vlolad commented on src/service/InMemoryHistoryManager.java
> +        //Нужно ли добавить проверку на пустой таск?
Она же уже есть

2024-10-10 07:26 UTC, vlolad commented on src/service/InMemoryHistoryManager.java
> +           removeNode(history.get(task.getId()));
Лучше всю логику удаления ноды перенести в removeNode, чтобы можно было просто передать (task.getId()). А дальше метод уже сам проверит наличие ноды в мапе, получит её и (если она не null) - разлинкует

2024-10-10 09:41 UTC, lapochka2019 commented on src/service/InMemoryHistoryManager.java
> +            previousNode.next = node.next;
Добрый день!
Согласна, протупила немножко)

2024-10-11 08:24 UTC, vlolad approved these changes
Привет!

Всё поправлено и принято)
Один комментарий, но он на улучшение, так что ещё итерация не нужна

Хорошего дня!

2024-10-11 08:24 UTC, vlolad commented on src/service/InMemoryHistoryManager.java
> +        Node node = history.get(id);
Если ключа в мапе нет, то возвращаться тоже будет null, так что верхнюю проверку можно убрать

2024-12-14 16:23 UTC, merged