Выполнен финальный проект 7 спринта
lapochka2019/java-kanban pull request #2
Opened 2024-12-16 19:07 UTC by lapochka2019

Добавлен класс: FileBackedTaskManager
Добавлен тест-класс: FileBackedTaskManagerTest
Добавлен Enum: Typea
Добавлены файлы .csv для тестов

2024-12-17 12:05 UTC, vlolad requested changes
Привет!

Всё отлично, работа аккуратно сделана без заметных багов. Есть только пару комментариев, из критичных - парсинг в строку/из строки (epicId есть не у всех типов задач) и определение idCounter при загрузке. Остальное на улучшение

Хорошего дня и с наступающим!

2024-12-17 12:05 UTC, vlolad commented on src/file/FileBackedTaskManager.java
> +        idCount = id;
Задачи могут сохраняться не по порядку id, так что лучше idCount обновлять только если он меньше id

2024-12-17 12:05 UTC, vlolad commented on src/file/FileBackedTaskManager.java
> +    public void getTaskFromString(String inputString) {
Лучше всего метод для перевода задачи в строку и из строки вынести в отдельный класс, например CSVConverter
Так как задачи можно и в другие форматы преобразовывать, конвертеры могут быть и другими. Зато класс не будет наполняться лишней логикой

2024-12-17 12:05 UTC, vlolad commented on src/file/FileBackedTaskManager.java
> +    public String toString(Task task) {
Не у всех видов задач есть epicId, надо учитывать

P.S. удобнее всего строку собирать с помощью класса StringJoiner, это аналог StringBuilder с возможностью сразу добавить разделитель между добавляемыми строками

2024-12-17 12:05 UTC, vlolad commented on src/file/FileBackedTaskManager.java
> +//ManagerSaveException
??
Забытый комментарий

2024-12-18 08:33 UTC, lapochka2019 commented on src/file/FileBackedTaskManager.java
> +    public void getTaskFromString(String inputString) {
Добрый день, Владислав!
Спасибо за ревью и рекомендации по улучшению кода.
Вынесла этот метод в другой класс, но боюсь "перемудрила". (Меня смущает, что есть вероятность возврата Null в данном методе, но я не придумала, как от нее избавиться)

2024-12-18 20:16 UTC, vlolad approved these changes
Привет!

Принято \(★ω★)/

2024-12-18 20:16 UTC, vlolad commented on src/file/CSVConverter.java
> +public class CSVConverter {
Отлично!

2024-12-19 04:49 UTC, merged